name: platform_buttons_stripe
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  pay: ^2.0.0
  http: ^1.2.1
  flutter_stripe: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
